# Generated by Django 5.0.11 on 2025-02-03 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('nombre_cientifico', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre_comun', models.CharField(blank=True, max_length=25)),
                ('extincion', models.BooleanField(blank=True, choices=[('Si', True), ('No', False)])),
                ('familia', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=25)),
                ('ciudad', models.CharField(blank=True, max_length=25)),
                ('pais', models.CharField(blank=True, max_length=25)),
                ('presupuesto', models.FloatField(blank=True)),
                ('tamañoMetrosCuadrado', models.FloatField(blank=True, verbose_name='Espacio')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('continente', models.CharField(choices=[('Europa', 'Europa'), ('Africa', 'Africa'), ('America del Sur', 'America del Sur'), ('America del Norte', 'America del Norte'), ('Oceania', 'Oceania'), ('Antartica', 'Antartica')], default='Africa', max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('especie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='especie_nombre', to='animal.especie')),
                ('zoo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='nombreZoo', to='animal.zoo')),
            ],
        ),
    ]
