# Generated by Django 5.1.2 on 2024-11-07 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_lenguaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lenguaje',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='lenguaje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.lenguaje'),
        ),
        migrations.AlterField(
            model_name='lenguaje',
            name='lenguage',
            field=models.CharField(default='español', max_length=100),
        ),
    ]
