# Generated by Django 5.1.2 on 2024-11-12 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_userx_authorx_publisherx_booksx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorx',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='authorx',
            name='recommendedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_authors', related_query_name='recommended_authors', to='catalog.authorx'),
        ),
    ]
