# Generated by Django 5.1.2 on 2024-11-12 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_authorx_address_alter_authorx_recommendedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisherx',
            name='recommendedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.publisherx'),
        ),
    ]
