# Generated by Django 4.2.16 on 2024-12-08 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_publisherx_recommendedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksx',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books2', related_query_name='books', to='catalog.publisherx'),
        ),
    ]
