# Generated by Django 5.1.2 on 2025-01-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_usuariox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariox',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuariox',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
