# Generated by Django 5.1.2 on 2025-01-16 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_usuariox_email_alter_usuariox_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuarioX',
        ),
    ]
