# Generated by Django 5.1.2 on 2025-01-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_usuariox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariox',
            options={},
        ),
    ]
