# Generated by Django 5.1.2 on 2025-01-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_usuariox_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariox',
            options={'permissions': (('calculadoraAcceso', 'Acceso a calculadora'),)},
        ),
    ]
