# Generated by Django 4.2.16 on 2025-02-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_usuariox_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='libros/portadas/'),
        ),
    ]
