# Generated by Django 4.2.16 on 2025-02-19 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_book_portada'),
    ]

    operations = [
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(blank=True, max_length=500)),
                ('nombre', models.CharField(blank=True, max_length=600)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('idAutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.usuariox')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.bookinstance')),
            ],
        ),
        migrations.CreateModel(
            name='votos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.bookinstance')),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.usuariox')),
            ],
        ),
        migrations.CreateModel(
            name='solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to='catalog.usuariox')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to='catalog.usuariox')),
            ],
        ),
        migrations.CreateModel(
            name='mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=500)),
                ('destinatario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajerecibido', to='catalog.usuariox')),
                ('remitente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajeEnviado', to='catalog.usuariox')),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplares_lectores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('leido', 'leido'), ('leyendo', 'leyendo'), ('pendiente', 'pendiente')], default='pendiete', max_length=10)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.comentario')),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.bookinstance')),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.usuariox')),
            ],
        ),
        migrations.AddField(
            model_name='usuariox',
            name='amigos',
            field=models.ManyToManyField(related_name='amigos_relacionados', through='catalog.solicitud', to='catalog.usuariox'),
        ),
        migrations.AddField(
            model_name='usuariox',
            name='votosEjemplares',
            field=models.ManyToManyField(through='catalog.votos', to='catalog.bookinstance'),
        ),
    ]
